2019-10-11 02:31:15,037 ERROR: Exception on /recipes/alchemy [GET] [in c:\users\evan\anaconda3\envs\fate\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Evan\documents\fate\app\routes.py", line 78, in recipes
    profession[0] = profession[0].upper()
TypeError: 'str' object does not support item assignment
2019-10-11 02:31:44,356 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 02:32:14,524 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 02:35:27,148 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 02:50:04,372 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 02:57:43,368 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 03:05:59,921 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 03:07:52,352 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 03:12:47,971 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 03:14:08,704 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 03:15:31,698 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 03:16:02,891 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 03:41:59,852 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 03:45:12,890 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 03:48:25,363 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 03:49:12,012 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 03:49:31,417 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 03:51:13,053 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 03:51:37,057 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 03:56:13,414 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 03:56:44,466 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 03:57:52,705 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 03:58:16,220 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 03:58:28,119 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 04:01:44,253 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 04:01:44,991 ERROR: Exception on /user/Evan [GET] [in c:\users\evan\anaconda3\envs\fate\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Evan\documents\fate\app\routes.py", line 57, in user
    return render_template('user.html', user=user)
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Evan\documents\fate\app\templates\user.html", line 11, in template
    {% if user.profession_one is not 'None' %}<p>Profession 1: {{ user.profession_one }}</p>{% endif %}
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 211, in parse_if
    node.test = self.parse_tuple(with_condexpr=False)
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 620, in parse_tuple
    args.append(parse())
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 612, in <lambda>
    parse = lambda: self.parse_expression(with_condexpr=False)
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 433, in parse_expression
    return self.parse_or()
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 450, in parse_or
    left = self.parse_and()
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 459, in parse_and
    left = self.parse_not()
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 470, in parse_not
    return self.parse_compare()
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 474, in parse_compare
    expr = self.parse_math1()
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 496, in parse_math1
    left = self.parse_concat()
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 507, in parse_concat
    args = [self.parse_math2()]
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 517, in parse_math2
    left = self.parse_pow()
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 528, in parse_pow
    left = self.parse_unary()
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 549, in parse_unary
    node = self.parse_filter_expr(node)
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 687, in parse_filter_expr
    node = self.parse_test(node)
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\parser.py", line 827, in parse_test
    name = self.stream.expect('name').value
  File "c:\users\evan\anaconda3\envs\fate\lib\site-packages\jinja2\lexer.py", line 384, in expect
    self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: expected token 'name', got 'string'
2019-10-11 04:03:51,351 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 04:05:45,135 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
2019-10-11 15:09:33,287 INFO: Fate startup [in C:\Users\Evan\documents\fate\app\__init__.py:46]
